# Generated by Django 4.1 on 2022-09-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspendedList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_suspended", models.BooleanField(default=False)),
            ],
        ),
    ]
