name: Prod CI

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: deploy code
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            rm -rf tatis
            git clone git@github.com:ryancheley/tatis.git

            source /home/tatis/venv/bin/activate

            cd /home/tatis/

            rm -rf /home/tatis/tatisjr

            cp -r /root/tatis/ /home/tatis/tatisjr

            cp /home/tatis/.env /home/tatis/tatisjr/tatisjr/.env

            pip -q install -r /home/tatis/tatisjr/requirements/production.txt

            python /home/tatis/tatisjr/manage.py migrate

            mkdir /home/tatis/tatisjr/static

            python /home/tatis/tatisjr/manage.py collectstatic --noinput -v0

            systemctl daemon-reload
            systemctl restart tatis