name: Prod CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: deploy code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            rm -rf tatis
            git clone git@github.com:ryancheley/tatis.git

            source /home/tatis/venv/bin/activate

            cp -r tatis/* tatisjr/

            python -m pip install --upgrade pip

            pip -q install -r /home/tatis/tatisjr/requirements/production.txt

            python /home/tatis/tatisjr/manage.py migrate

            python /home/tatis/tatisjr/manage.py collectstatic --noinput -v0

            sudo systemctl daemon-reload
            sudo systemctl restart tatis
