name: Prod CI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: deploy code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            git clone git@github.com:ryancheley/tatis.git

            source /home/tatis/venv/bin/activate

            rsync -av --delete --exclude=.env tatis/* tatisjr

            pip -q install -r /home/tatis/tatisjr/requirements.txt

            python /home/tatis/tatisjr/manage.py migrate

            python /home/tatis/tatisjr/manage.py collectstatic --noinput -v0

            sudo systemctl daemon-reload
            sudo systemctl restart tatis

            rm -rf tatis
